### ISSUE TITLE
Class 'Google_Client' not found

### ISSUE THREAD

**Issue by dunets** [rainlab/googleanalytics-plugin#67] opened 2017-08-05 15:01 UTC
An error `Class 'Google_Client' not found` appears on the dashboard, after adding statistics panel...

![image](https://user-images.githubusercontent.com/6217617/28996362-ec338f92-79f6-11e7-9942-a1b63ce6a25a.png)

Google Analytics version 1.2.1
October  build 419

**Comment by Daugirdas** [comment] 2017-08-05 20:13
You need to install [Google APIs Client Library for PHP](https://github.com/google/google-api-php-client)

**Comment by ametad** [comment] 2017-08-08 13:34
How did you install the plugin?

**Comment by woodinteractive** [comment] 2017-08-10 00:27
@ametad some problem here. Ran in Client Library install. No change.

**Comment by ametad** [comment] 2017-08-10 07:32
@woodinteractive I am sorry, I don't understand what "Client Library install" means. Could you explain?

When you install this plugin through the backend in OctoberCMS or on the command line with:
```
$ php artisan plugin:install rainlab.googleanalytics
```

Then the dependencies are installed also.

It will NOT work when you just copy the files from this repository in your plugins/ directory. Because the dependencies must be retrieved in the installation process.

**Comment by Daugirdas** [comment] 2017-08-10 10:42
Dependencies are other OctoberCMS plugins. [Google APIs Client Library for PHP](https://github.com/google/google-api-php-client) is not.  To install follow instructions on github. I personally installed it in app root folder with
`composer require google/apiclient:^2.0`
That's it.

**Comment by dunets** [comment] 2017-08-10 10:50
@ametad  I installed the plugin with the october backend installer...
to solve that problem, I copied `composer.json` from the google analytics plugin repository
into the google analytics plugin, then I ran `composer update` from project root

**Comment by ametad** [comment] 2017-08-10 11:35
@dunets You did install it with the backend... well that is strange(!) it didnot install the composer dependencies. Because that is the way it works normally. This could be a bug.

**Comment by dunets** [comment] 2017-08-10 11:39
@ametad yes on my local development  everything works well, but not on a production server... I need to install many things manually with composer and I have bugs like that...

**Comment by ametad** [comment] 2017-08-10 11:58
What is the difference between your local and production? I think there lies the answer to your problems...

**Comment by ametad** [comment] 2017-08-10 12:48
Hmm... The last install I did was about three month ago, no problems then.
But now I have this problem too of the missing Google_Client Class! 

I did:

-  a clean install of October build 419
-  then installed this plugin
-  configured the settings
-  added an analytics widget to the dashboard

The problem is indeed that for some reason the dependencies are not installed properly in this new installation. Unlike previous installations where the Google_Client class is just to be found! 

I am not sure what the problem is... because I have seen a 'vendor' map here: plugins/rainlab/googleanalytics/vendor
When I make a plugin and define composer requirements, those are downloaded to the root vendor map, and not into the plugins folder.

So what is going on here?

**Comment by ametad** [comment] 2017-08-10 12:57
In this project's composer.json ```"google/apiclient": "^2.0.0@RC"``` is required. Pay attention to '@RC'... 

The docs (https://github.com/google/google-api-php-client/blob/master/README.md) mention:
```
composer require google/apiclient:^2.0
```

Perhaps  '@RC' is wrong?

**Comment by ametad** [comment] 2017-08-10 15:04
When I make a plugin and submit it to the OC Market, it is without vendor map (and with composer.json). But when this plugin is installed on a october instance, the vendor map has been included in the folder where the plugin resides. 

I must admit; I don't know exactly how this vendor map in the plugin's directory has got there?!

**Comment by ametad** [comment] 2017-08-17 16:02
https://stackoverflow.com/questions/45622700

Answer is that the vendor map in the plugins folder should be got there by running the update process.

**Comment by LukeTowers** [comment] 2017-08-18 21:35
The octobercms.com marketplace build process pulls in the plugin’s dependencies into a vendor directory under the plugin’s own directory and then removes composer.lock and composer.json from the package that gets generated. This is to support users that don’t use composer while also supporting users that use both marketplace plugins and composer-based plugins.

If we left the composer.json in the plugin during the build process and then the user were to run composer update from the project root on that marketplace plugin, suddenly they would have duplicated dependencies which was causing a lot of issues.

All of this to say: Don't include your vendor directory when submitting a plugin to the marketplace, the marketplace will take care of that. Do include your composer.json file though.

In regards to RainLab.GoogleAnalytics, the build on the marketplace appears to be broken which means that it needs to be rebuilt on the marketplace. This could be triggered by pushing an update to the Github repository, which I haven't been able to until @ametad pointed out that adblockers occasionally cause problems with Github repositories.

**Comment by LukeTowers** [comment] 2017-12-21 22:11
This should be fixed now that the marketplace has rebuilt the plugin for the last version release.

**Closed by LukeTowers** 2017-12-21 22:11 UTC
Labels: Status: In Progress, Type: Bug
