### ISSUE TITLE
Adding a Google Analytics widget crashes the dashboard

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [rainlab/googleanalytics-plugin#31] opened 2015-12-05 06:51 UTC
I get a `Google_Client::setClassConfig` error when I add any of the plugin's widgets to the dashboard. Here’s a screenshot of the stack trace:

![Screenshot](http://i.imgur.com/rLOyrJ3.png)

**Comment by seanthepottingshed** [comment] 2015-12-10 10:30
Exactly the same issue here - any ideas?

**Comment by SaifurRahmanMohsin** [comment] 2015-12-10 11:22
I made a fresh install of OctoberCMS and installed the plugin and it works fine now. Hopefully I won’t see this again..!

**Comment by WebShapedBiz** [comment] 2015-12-12 17:44
Same here. If there is anything wrong with plugin configuration, and help file is not current since Google is always changing its UI, you can kiss your backend goodbye. That is just awful, I suggest that you either fix this ASAP or remove from plugins because this plugin can cause a lot of problems to admins.

**Comment by MatissJanis** [comment] 2015-12-18 10:03
+1 the same problem here

**Comment by Colbydude** [comment] 2015-12-29 09:21
+1 here as well.

**Comment by faustoquaggia** [comment] 2015-12-30 15:00
+1

**Comment by abelschooleman** [comment] 2015-12-31 20:30
Just ran into the same issue. Removing the widgets from my dashboard in the backend_user_preferences table gave me access to the dashboard again.

**Comment by tobycatlin** [comment] 2016-01-05 13:41
I have just hit this after installing the plugin and config

**Comment by sNuuFix** [comment] 2016-01-09 10:17
It seems that Google API included in latest plugin is from wrong branch, it's master, but it should me v1-master.

The simplest temporary fix is to remove plugins/rainlab/googleanalytics/vendor/google/apiclient directory, then add the correct one. Just cd into plugins/rainlab/googleanalytics/vendor/google and run 'git clone -b v1-master https://github.com/google/google-api-php-client.git apiclient'

When this will get fixed, just remove and add the plugin again, but updating it after doing this fix may break things badly.

**Comment by daftspunk** [comment] 2016-01-11 10:58
Should be fixed in v1.0.6

**Comment by WebShapedBiz** [comment] 2016-01-11 11:08
Thank you @daftspunk

**Comment by SaifurRahmanMohsin** [comment] 2016-01-11 11:09
Great! Thank you.

**Comment by Colbydude** [comment] 2016-01-11 17:51
Fixed here as well, thanks!

**Comment by daftspunk** [comment] 2016-01-11 20:28
This was caused by a fault in composer, downloading unnecessary dependencies that conflict with the Drivers plugin. Solved by importing the Google library manually.

**Closed by daftspunk** 2016-01-11 20:28 UTC
