### ISSUE TITLE
Dashboard Widget Giving Permissions Error

### ISSUE THREAD

**Issue by kombimedia** [rainlab/googleanalytics-plugin#108] opened 2021-01-15 00:56 UTC
Hi There,

I am getting a permissions error when adding a widget to the dashboard.

    { "error": { "code": 403, "message": "User does not have sufficient permissions for this profile.", "errors": [ { "message": "User does not have sufficient permissions for this profile.", "domain": "global", "reason": "insufficientPermissions" } ] } }

CMS v1.0.7
PHP v7.4.7
Plugin v1.3.0

I noticed that Goggle have changed their tracking code, could this be the issue?

Any ideas?

Cheers, Cy

**Comment by bennothommo** [comment] 2021-01-15 04:08
@kombimedia It may be that the plugin is incompatible with Google Analytics v4, if you are using that. See https://github.com/rainlab/googleanalytics-plugin/issues/101 for more info. Otherwise, this is a duplicate of https://github.com/rainlab/googleanalytics-plugin/issues/83 and you'll need to check your permissions on the Google Analytics side.

**Closed** 2021-01-15 04:08 UTC
Labels: duplicate

**Comment by kombimedia** [comment] 2021-01-18 00:00
Great thanks @bennothommo
